### ISSUE TITLE
Potential energy in small cells

### ISSUE THREAD

**Issue by magnusrahm** [brucefan1983/GPUMD#110]
Hi,

I've been trying out GPUMD lately, and it has worked very smoothly. However, I have come across one pitfall that may be a bug or at least a somewhat unexpected behavior that I couldn't find any mention of in the user guide. The potential energy per atom in very small cells differs from the corresponding quantity in large cells. It seems like more long-ranged models converge slower than short-ranged ones when cell size is increased, so my guess is that it has to do with handling of periodic images. It seems like the behavior is the same independent of type of potential, cell shape (cubic vs non-cubic), and the choice of cutoff in `xyz.in`.

Is this a known behavior and can I avoid it without repeating my cell sufficiently?

Below is an output of energy per atom for three different Si potentials, with potential energy calculated for cells with different number of atoms (just repeated along periodic boundary conditions):

```
tersoff       2 atoms, potential energy: -1.571410841
tersoff      16 atoms, potential energy: -4.6296117249375
tersoff      54 atoms, potential energy: -4.629611725
tersoff     128 atoms, potential energy: -4.629611724921875
tersoff     250 atoms, potential energy: -4.6296117248
tersoff     432 atoms, potential energy: -4.629611725

sw            2 atoms, potential energy: -1.0841295637
sw           16 atoms, potential energy: -4.336518254875
sw           54 atoms, potential energy: -4.336518254814815
sw          128 atoms, potential energy: -4.33651825484375
sw          250 atoms, potential energy: -4.3365182548000005
sw          432 atoms, potential energy: -4.336518254861111

nep           2 atoms, potential energy: -2.7376508713
nep          16 atoms, potential energy: -2.5197944939375
nep          54 atoms, potential energy: -2.2679282692592593
nep         128 atoms, potential energy: -2.267928259453125
nep         250 atoms, potential energy: -2.2679282560400003
nep         432 atoms, potential energy: -2.2679282542824075
```

Representative `run.in`:
```
potential      ../potentials/tersoff/Si_Fan_2019.txt 0
velocity       0.001
dump_thermo    1
time_step      1e-6
run            1
```

Representative `xyz.in` (repeat=1):
```
2 1024 10 1 0 0 
1 1 1 0.0 2.715 2.715 2.715 0.0 2.715 2.715 2.715 0.0 
0 0.0 0.0 0.0 28.085
0 1.3575 1.3575 1.3575 28.085
```

Everything needed to reproduce this:
[debug.zip](https://github.com/brucefan1983/GPUMD/files/7552946/debug.zip)

I've been using the dev version at bbd724d5737160fc18ae41783b62be0e6a845d8d

Best,
Magnus Rahm

**Comment by brucefan1983** [comment]
Dear Magnus,

Thanks for the question. What you have seen are expected, as GPUMD uses the minimum-image convention to handle periodic systems. That is, the user needs to make sure that the box thickness in each periodic direction is larger than twice of the largest cutoff distance (note that the cutoff distance for the global neighbor list could be larger than the largest force cutoff, depending on the third parameter specified in the first line of `xyz.in` and the parameter for the `neighbor` keyword in `run.in`). This is quite different from the LAMMPS convention, but is the same as used in GROMACS.

I have just added some descriptions to the manual to emphasize this convention: https://gpumd.zheyongfan.org/index.php/The_xyz.in_input_file#Line_1

That said, the executable `nep` for training the NEP potential will replicate a cell sufficiently and the training/testing structures in `train.in` / `test.in` can be small ones such as primitive cells.

Zheyong

**Comment by magnusrahm** [comment]
Dear Zheyong,

Thank you very much for the quick and clear response! The addition to the manual is excellent.

Magnus

**Comment by brucefan1983** [comment]
Now the NEP model supports small boxes, but the empirical potentails still do not.
