### ISSUE TITLE
Add option to consider convective heat current in thermal conductivity calculations

### ISSUE THREAD

**Issue by brucefan1983** [brucefan1983/GPUMD#112]
This is important for fluids and might also have small effects in some solid structures.

**Comment by hityingph** [comment]
It might also be important for some glasses or amorphous solids, which have bigger difussion property when compared with the lattice structures.

**Comment by brucefan1983** [comment]
We are still studying this. I really want to figure out the role of convection from solid to fluid. I also want to extend the spectral decomposition techniques to more general systems. This might lead to a nice paper.

**Comment by brucefan1983** [comment]
It turned out that the convection part is very small (about 10%) even for liquids. And there is no need to do spectral decomposition for the convection part, as it must be at zero frequency.

**Comment by brucefan1983** [comment]
will be solved in #449

**Comment by brucefan1983** [comment]
close as solved.
