### ISSUE TITLE
Relative path for nep.txt when running nep md

### ISSUE THREAD

**Issue by FotbollsJoel** [brucefan1983/GPUMD#149]
I made a scheme for running many md:s from different folders, placing a nep.txt file in each folder (among other input files). Alas, running gpumd in with this scheme did not work, as the local nep.txt (as specified as 'nep.txt' in the loacal run.in file) could not be found. I assume this is not intended and to clarify a bit further: I got around it through making a really hacky bash script like this:

#!/usr/bin/env bash
cd /home/anjoel/Master/GPUMD/gpumd_nep/md_out_1/nep1_run1_xyz
gpumd < input_gpumd.txt
cd /home/anjoel/Master/GPUMD/gpumd_nep/md_out_1/nep1_run2_xyz
gpumd < input_gpumd.txt
...

**Comment by brucefan1983** [comment]
Although I used relative path (should be relative to the GPUMD main folder) to describe the examples/tutorials, you can always use absolute path in `run.in`:

```
potential  absolute/path/to/your/nep.txt 0 1 2 ... # the numbers here depend on the potential
```

**Comment by brucefan1983** [comment]
So if you are using the same nep.txt, it is even better to put it somewhere (such as `potentials/nep/your_folder/` and use this same file in `run.in`.

**Comment by brucefan1983** [comment]
To explain further: whenever you use relative path, it is relative to the place where you run the executable. This is why I emphasized in this page (https://github.com/brucefan1983/GPUMD/tree/master/examples): 

"Then, go to the **directory** where you can see src and type one of the following commands to run something:"

In this way, all my relative paths are relative to this particular **directory **.

**Comment by FotbollsJoel** [comment]
Thank you. I thought this was maybe unintended, but it's not really an issue then.

**Comment by brucefan1983** [comment]
Yes the behavoirs you saw are expected. The very purpose of using the "driver input file" is to enable running a series of simulations using a single launch of the executable without writing a shell script.
