### ISSUE TITLE
Implement NEP2 program in the latest version

### ISSUE THREAD

**Issue by Jonsnow-willow** [brucefan1983/GPUMD#153]
I think NEP2 program is not bad in accuracy and faster in fitting potentials of pure metal. I hope to use NEP2 potential in the latest version.

**Comment by brucefan1983** [comment]
Thanks! So I think what you want is to use
```
version version_number
```
to choose between NEP2 and NEP3 I think.

I will bring NEP2 back and make it coexist with NEP3 in the latest version.

**Comment by brucefan1983** [comment]
NEP2 is back in master, see this PR: #155 
Also fixed a bug for small-box MD with NEP (any version of NEP)
