### ISSUE TITLE
About the install for GPUMD

### ISSUE THREAD

**Issue by maverick422** [brucefan1983/GPUMD#166]
when i installing GPUMD-3.2 through tar.gz in linux  without root 
it goes 
`nvcc -std=c++11 -O3 -arch=sm_86 -DUSE_NEP -I./ -c main_gpumd/cohesive.cu -o main_gpumd/cohesive.o
make: execvp: nvcc: 权限不够
make: *** [main_gpumd/cohesive.o] 错误 127
`
i tried the chmod , Only get the same result
thanks for your help!

**Comment by brucefan1983** [comment]
This should be related to `nvcc` in your system (account). Could you check if you can compile a simple CUDA code like this:

```
#include <stdio.h>

__global__ void hello_from_gpu()
{
    printf("Hello World from the GPU!\n");
}

int main(void)
{
    hello_from_gpu<<<1, 1>>>();
    cudaDeviceSynchronize();
    return 0;
}
```

Put the code above into a file such as `hello.cu` and try to compile it using `nvcc hello.cu` to see what happens.

**Comment by maverick422** [comment]
Indeed it is. It turns out that my environment variable CUDA was Commented out. Everthing goes fine after i buring it back. Thanks a lot!

**Comment by brucefan1983** [comment]
That's great.
