### ISSUE TITLE
Could you please output step 0 in dump.xyz (and movie.xyz, restart.out) ? thanks !

### ISSUE THREAD

**Issue by grtheaory** [brucefan1983/GPUMD#186]
Step 0 is a frequently needed reference for batch post-processing of dump.xyz (and movie.xyz, restart.out ). 
Could you please output step 0? 
Thanks!

**Comment by brucefan1983** [comment]
Thanks for this good suggestion. I will do it at some point.

**Comment by brucefan1983** [comment]
This involves many regression tests so I need to do it carefully.

**Comment by brucefan1983** [comment]
Actually, the best way of achieving your purpose is to use a `run.in` like this:

```
potential   potentials/tersoff/Si_Fan_2019.txt 0
velocity    1000

# just to get the initial frame here
ensemble    nve
time_step   0   # zero time step ensures that the atom will not move during this NVE run
neighbor    off
dump_exyz   1 0 0
run         1

# your other simulations
ensemble    npt_ber 1000 1000 100 0 0 0 53.4059 53.4059 53.4059 2000
time_step   1
neighbor    off
dump_exyz   10 0 0
run         100
```

So there is no need to change the source code of GPUMD.
