### ISSUE TITLE
No neighbor list building by default?

### ISSUE THREAD

**Issue by andeplane** [brucefan1983/GPUMD#2]
By reading the docs, it seems like if I don't specify `neighbor` command in the run.in script, neighbor list is not being rebuilt during the simulation. This seems to be correct based on performance numbers as well.

Isn't this a huge pitfall for users? Default value should be that it will build whenever it is needed, yes?

**Comment by andeplane** [comment]
I ran a pure silicon system, 27000 atoms on a 2d surface with a certain thickness ( a few unit cells ). 
Without `neighbor` keyword I got ~3.0e8 atomtimesteps/s (wow), but if I use the `neighbor` keyword, it drops to 2.14e8 which is still good, but a rather huge part of simulation time is on building neighbor list?

**Comment by brucefan1983** [comment]
Thank you very much for this comment. Yes, the neighbor list is not updated by default. This is due to historical reason, as I have only been interested in studying stable solids. I have never studied fluids in my previous researches. You are right that it may be better to update the neighbor list by default but let the user to switch it off if she/he wants to.

But I am surprised that the neighbor list update is so time consuming from your test. Should we check this out in more detail?

**Comment by andeplane** [comment]
I don't think it actually consumes that much, but that the simulation isn't doing what it should :)

**Comment by andeplane** [comment]
nvprof shows that 
gpu_find_force ~54%,
neighbors ~28%
find_thermo is ~13%

**Comment by brucefan1983** [comment]
This sounds normal. Why the performance drop by a few factors when updating the neighbor list?

**Comment by andeplane** [comment]
Yep, that sounds normal. So in the case where I get wrong timesteps/second it is probably because neighborlists are empty or something...

**Comment by andeplane** [comment]
I see. The way LAMMPS does it is having a box size defined as rmin = [min(x), min(y), min(z)], rmax = [max(x), max(y), max(z)], a number that changes every timestep. But you only use this when you build the cell list.

**Comment by brucefan1983** [comment]
Oh, so simple. Is this the so-called shrink-wrapping boundary conditions? I will try to use this in the neighbor list functions.

**Comment by andeplane** [comment]
Yeah think so :)

**Comment by brucefan1983** [comment]
Now I have printed the number of neighbor list updates for each run, similar to LAMMPS. When the `neighbor` command is used for a run, the number of neighbor list updates must be 0. This information should remind the user about the neighbor list stuff. I still want to keep the old way: not updating by default and only do it when the `neighbor` command is used for a run. This is just a convention.
