### ISSUE TITLE
File mismatch error when running gpumd or nep in windows platform

### ISSUE THREAD

**Issue by hityingph** [brucefan1983/GPUMD#202]
When running simulations (or trainning) in windows platform, the gpumd package sometimes reports the error of "File size mismatch". This bug should be fixed as soon as possible.

**Comment by brucefan1983** [comment]
could you try to remove the following lines and try:

![image](https://user-images.githubusercontent.com/24891193/171990239-15917704-894a-4609-800e-6fb835595e22.png)

**Comment by brucefan1983** [comment]
as we discussed offline, this can be closed.
