### ISSUE TITLE
Add options to determine whether to output d.out

### ISSUE THREAD

**Issue by hityingph** [brucefan1983/GPUMD#209]
For very complex system containing several hundered atoms in primitive cell， when using [compute_phonon](https://gpumd.zheyongfan.org/index.php/The_compute_phonon_keyword), the size of [D.out](https://gpumd.zheyongfan.org/index.php/The_D.out_output_file) can be extremely large (tens of GB). Therefore, can we add a option to determine whether to output d.out?

**Comment by brucefan1983** [comment]
Thanks for the nice suggection. I will check it at some point.

**Comment by hityingph** [comment]
After discussion with Zheyong, this issue is not very urgent. Maybe he will fix this problem when he begin to work on BTE module.
