### ISSUE TITLE
GPUMD output is buffered by 4096 bytes 

### ISSUE THREAD

**Issue by Youjin1985** [brucefan1983/GPUMD#212]
Hello,
When I run program like gpumd < gpumd_in.txt | tee gpumd.out
text appears on screen only when 4096 characters of output was produced.
When I do not redirect to file, output appears normally at same time.
Please make output unbuffered - described behaviour is not convenient to keep what is going on with calculation.

**Comment by brucefan1983** [comment]
Thanks for reporting this. It is expected behavior and I will consider improving it at some point.

**Comment by brucefan1983** [comment]
solved in this PR: #219
