### ISSUE TITLE
unified memory?

### ISSUE THREAD

**Issue by Kick-H** [brucefan1983/GPUMD#216]
I can't run some commands on the virtual machine:
compute_hnemd, compute_shc and compute_emd et al.

This is the errors:
<img width="451" alt="4157b4ccc2e125688f489c78257999a" src="https://user-images.githubusercontent.com/30561696/179226765-9559423b-b5dd-4b2d-88cd-05223291d163.png">

This is the run.in:
<img width="447" alt="8730f9a61c2fe793e67e409a8600edc" src="https://user-images.githubusercontent.com/30561696/179226773-2bfe655a-b757-4fad-81c9-73c85efa8b56.png">

**Comment by brucefan1983** [comment]
Solve in this PR: #217 

Because the master version now contains some changes regarding `nep.txt`, I suggest you simply copy the `src/measure/hac.cu` and `src/measure/shc.cu` files from the master version to your current version. Then you can build the code and start to use your powerful V100!

**Comment by Kick-H** [comment]
thanks.
