### ISSUE TITLE
Optimization stuck at two points

### ISSUE THREAD

**Issue by ZKC19940412** [brucefan1983/GPUMD#221]
Dear developers for NEP potential:
Hi, when I try to develop an NEP potential with a certain set of data, the training RMSE shows exact same pattern for energy and force in between optimization steps, which to me means it stuck at two points. I wonder what could have caused the issue and how to solve it. I have made sure the input are in proper units as instructed in the manual website.  I have attached the loss.out , energy and force_train.out in case you want to play around with it and I used GPUMD v3.3.1 for the nep potential construction. 
[wired optimization process.zip](https://github.com/brucefan1983/GPUMD/files/9143724/wired.optimization.process.zip)

Thank you so much for answering my question.

**Comment by brucefan1983** [comment]
The results you obtained are indeed abnormal and I think there are some input errors. 

The reference forces look reasonable, which are of the order of  ~eV/A. 

The reference energies, on the other hand, are about -156 eV/atom, and I guess they were not from VASP, but from, say, CP2K?

Have you paid attention to the box matrix? The box matrix follows the convention of VASP, and the elements are in the following order: `ax, ay, az, bx, by, bz, cx, cy, cz`.

I cannot tell anything for sure based on the provided data. If you do not mind, you can send me more data (here or privately using email) such as `nep.in`, `train.in`, and `test.in`, and a sample output file of original DFT calculations.

**Comment by ZKC19940412** [comment]
Thank you so much for the help and the required files are sent via email.
