### ISSUE TITLE
NPH emsemble

### ISSUE THREAD

**Issue by brucefan1983** [brucefan1983/GPUMD#238]
Good for melting point calculation.

**Comment by brucefan1983** [comment]
I have tried to use NPT with `tau_T = 1e10`, which seems to mimic NPH very well :-)

**Comment by brucefan1983** [comment]
Based on my test on melting simulation, NPH can be simply realized by setting `tau_T` to a large value such as `1e20`. Here is my `run.in`:
```
potential   ../../potentials/nep/Si_2022_NEP2.txt
velocity    600

time_step   2

ensemble    npt_scr 600 600 100 0 0 0 100 100 100 1000
dump_exyz   10000 0 0
run         10000

# generate liquid (2600 K) and solid (600 K) parts
ensemble    heat_lan 1600 100 1000 0 1 
dump_exyz   10000 0 0
run         10000

# use a large tau_T to mimic NPH
ensemble    npt_scr 1600 1600 1e20 0 0 0 50 50 50 1000
dump_thermo 100
dump_exyz   10000 0 0
run         100000
```

The figure below shows the temperature evolution and pressure evolution. The melting point is calculated to be 1.4666e+03 K, which is very close to that reported in https://doi.org/10.1103/PhysRevX.8.041048, from which I took the silicon training data to train a NEP model used here.

ping @erhart1  Do you agree with my opinion of getting NPH from NPT? I like this because there is no extra code. More over, the SCR barostat actually requires a targe temperature (just used a constant temperature), which is an input for NPT.

![image](https://user-images.githubusercontent.com/24891193/202220529-ad518b38-5365-4ea0-b985-b9c3a2ef19de.png)

**Comment by erhart1** [comment]
Thanks for the further extensive testing.
I was looking to do something similar ourselves but hadn't gotten to it yet.
I would be convinced if the enthalpy (E+pV) is conserved.
That is a prerequisite for the method to work.

**Comment by brucefan1983** [comment]
I will checkout that.

**Comment by brucefan1983** [comment]
Relative fluctuations of H=E+pV are up to 1%. Good or not?
![image](https://user-images.githubusercontent.com/24891193/202463865-701b14c2-b461-4d3a-92bb-04ec86f4cf48.png)

**Comment by erhart1** [comment]
Can you show them in meV/atom?

**Comment by brucefan1983** [comment]
![image](https://user-images.githubusercontent.com/24891193/202488484-150499bb-fb1b-4b04-a9f6-8703b9553220.png)

**Comment by erhart1** [comment]
I would consider those variations to be quite large. For an NVE simulation I would expect energy conservation to be at least 2 to 3 orders of magnitude better. No?

**Comment by brucefan1983** [comment]
Yes, in NVE 4 orders of magnitudes better. I will ask someone to try LAMMPS with the same NEP.

**Comment by brucefan1983** [comment]
![image](https://user-images.githubusercontent.com/24891193/202528470-0810e88b-e309-4bc7-992e-aaad6e8e6e5c.png)
I tried to use the Berendsen barostat and the conservation of  E+pV is about 5 times better. And the calculated melting point is also close: 1470 K.

**Comment by brucefan1983** [comment]
I also tried to comment out the temperature controlling part in Berendsen and the results are close to those from `tau_T=1e20`. So I think this is a feasible way to calculate the melting point. I also tried first NPH and then NVE and the results are similar. The purpose is just to get close to a target pressure and the true pressure can also be calculated.

**Comment by brucefan1983** [comment]
My current opinion: 
* Berendsen is not a well defined ensemble and I don't what should be conserved. 
* SCR has a conserved quantity but I have not implemented that. 
* These should be unimportant for melting point calculations, but more systematical calculations are needed. E.g. try to reproduce some well established results for Tersoff silicon.

**Comment by brucefan1983** [comment]
Tried your Tersoff (`Si_Erhart_2005_1.txt`) and got 2520 K, which is consistent with this paper: [Two-phase simulation of the crystalline silicon melting line at pressures from –1 to 3 GPa](https://aip.scitation.org/doi/10.1063/1.4739085)

**Comment by brucefan1983** [comment]
My last test, using `Si_Tersoff_1989.txt`, gives 2570 K , which is consistent with 2547 K as reported in [Comparison of semi-empirical potential functions for silicon and germanium](https://journals.aps.org/prb/abstract/10.1103/PhysRevB.47.7686).

**Comment by elindgren** [comment]
I've looked into running NPH simulations, both with a NEP model (for benzene) and a Tersoff potential (for carbon). I've followed your approach @brucefan1983 as in this issue. However, the simulation does not seem to be stable in my testing when setting `tau_T = 1e20`. See, for instance, these thermo properties from an NPH simulation in crystalline benzene:

![uncertainty_nep](https://user-images.githubusercontent.com/27208255/226909317-7d251741-95e2-4940-8de1-85a205c26380.png)

The enthalpy is conserved, except for a large dip at ~130 dump iterations. 

For a Carbon system with a Tersoff potential, the enthalpy is mostly conserved for short simulation times, but for larger times the system flies apart. 

![unstable](https://user-images.githubusercontent.com/27208255/226909682-f263447b-8035-4505-a307-d2c3009cc098.png)

Perhaps we should consider adding a proper NPH ensemble?

**Comment by brucefan1983** [comment]
Could you upload the inputs here such that I can reproduce the resutls and think about a possible solution?

**Comment by elindgren** [comment]
> Could you upload the inputs here such that I can reproduce the resutls and think about a possible solution?

[nph.tar.gz](https://github.com/brucefan1983/GPUMD/files/11060356/nph.tar.gz)

Here you go :) There are three subfolders, each corresponding to the systems (Benzene, C with a cubic cell and C with a triclinic cell).

**Comment by brucefan1983** [comment]
The problem should be mostly from the too large time steps. 
- For benzene with H atoms, a time step is 1 fs is definitely too large. For water, one usually uses 0.1 fs or at most 0.2 fs.
- For carbon at high temperature, a time step of 1 fs might be ok for the NEP model as in our JCP paper, but is definitely too large for the Tersoff potential. You might know Tersoff has anomalously large forces around the cutoff. I tried 0.5 fs and the results look ok, but I think a more conservative value is 0.2 fs.
- Also need to increase `tau` when you decrease the time step.

**Comment by elindgren** [comment]
> The problem should be mostly from the too large time steps.

I thought that 1 fs should be enough for hydrogen. Is it common to use so small time steps during NPH-simulations, or is it done in any system with hydrogen? In my experience, 1fs has usually been enough during "normal" MD simulations in NVT/NPT etc.

**Comment by brucefan1983** [comment]
For systems with dydrogen, a times step of 0.25 fs should be the highest that can be used in non-thermostatted situations. Thermostats (particularly Langevin) can help to stabilize by damping the velocity.

**Comment by brucefan1983** [comment]
Both papers below used 0.1 fs for water:

liquid:
https://arxiv.org/abs/2302.12328
solid:
https://aip.scitation.org/doi/10.1063/5.0022013

**Comment by brucefan1983** [comment]
Any further investigation on this? One possible improvement in the code is to totally remove the thermostat when `tau_T` is large.

**Comment by elindgren** [comment]
> Any further investigation on this? One possible improvement in the code is to totally remove the thermostat when `tau_T` is large.

I haven't had the time to look into this much further. I'll update this issue when I get around to it. Do you want to close the issue in the meantime, or should we let it be open?

**Comment by brucefan1983** [comment]
The issue can be kept open. I just wonder if some improvement can be done regarding this.

**Comment by brucefan1983** [comment]
I have just improved the NPH ensemble for the Berendsen method a little. Now when the temperature coupling parameter is larger than 100000 time step, the Berendsen thermostat is completely ingnored, leaving the barostat only. In this case the NPT ensemble is reduced to the NPH ensemble. 

I tried similar tricks for SCR but it surprisingly leads to strong artifacts. I don't know what's going on. It seems the SCR barostat is only working with the BDP thermostat, and cannot not work without it. I also have not made SCR barostat working with PIMD.

Anyway, for melting point calculations, there is no need to care about the true NPH or NPT ensemble. The major point is to control the pressure to the target. 

We have tried this method for 18 metals and the results are quite robuts (reproducible).

**Comment by erhart1** [comment]
Incidentally I just tested this for Al. I found the initial kinetic energy input to be not entirely conserved. But it works for the purpose of computing the melting point with good accuracy

**Comment by erhart1** [comment]
While I would prefer a full NPH ensemble, I don't think this is a priority atm. I suggest closing the issue

**Comment by brucefan1983** [comment]
@erhart1  Thanks for the confirmation. I also believe there is no problem for the purpose of melting point calculations. I will close this issue and go back it when we really need a true NPH ensemble for some applications.
