### ISSUE TITLE
multi-NEP models in a single simulation

### ISSUE THREAD

**Issue by brucefan1983** [brucefan1983/GPUMD#239]
* use case 1: on-the-fly calculation of model uncertainty
* use case 2: multiple different PESs are needed for e.g., ground and excited states

**Comment by ZengZezhu** [comment]
Yes, the uncertainty measurement is necessary for making sure the reliability of NEPs (just like the committee model of this paper: https://aip.scitation.org/doi/abs/10.1063/5.0016004).

**Comment by erhart1** [comment]
ping @elindgren as discussed
