### ISSUE TITLE
File mismatch error when running gpumd or nep in windows platform

### ISSUE THREAD

**Issue by hityingph** [brucefan1983/GPUMD#246]
When running simulations (or trainning) in windows platform, the gpumd package sometimes reports the error of "File size mismatch". I have raised this isuue previously, however, it has not been perfectly fixed. This bug should be fixed as soon as possible.

**Comment by brucefan1983** [comment]
Could you upload your run.in such that I can reproduce the problem?

**Comment by hityingph** [comment]
@brucefan1983 Attached please find the "run.in", "model.xyz", and potential files used in the master version.
[file_mismatch.zip](https://github.com/brucefan1983/GPUMD/files/9450537/file_mismatch.zip)

**Comment by brucefan1983** [comment]
I will look into this ASAP. I also encountered this problem sometimes. It's time to use modern C++ to deal with the `run.in` file now.

**Comment by brucefan1983** [comment]
I tried to fix this but failed to find a simple way. To fix this, I might need re-write the whole part parsing `run.in`. I would like to postpone this to the next release.

**Comment by brucefan1983** [comment]
solved in PR #310
