### ISSUE TITLE
Report the number of neighbor atoms in the simulation process

### ISSUE THREAD

**Issue by Jonsnow-willow** [brucefan1983/GPUMD#259]
In some severe situations such as radiation damage, the artificially prepared training set may not cover the whole process. The report of the number of neighbor atoms may help us to update the training set.

**Comment by brucefan1983** [comment]
Thanks for the suggestion, I will report the neighbor list information to the screen.

**Comment by brucefan1983** [comment]
now if you add `-DJIAHUI` to `makefile`, you will get neighbor list info every 1000 steps for the single-GPU version of NEP. 

I have not decided how to do it in a better way, and this fix is only for you.

**Comment by Jonsnow-willow** [comment]
Thanks
