### ISSUE TITLE
implementing the general SW potential 

### ISSUE THREAD

**Issue by brucefan1983** [brucefan1983/GPUMD#27]
@AlexGabourie 
Do you want to make a general SW potential applicable to an arbitrary number of atom types, similar to your Tersoff1988? We can also remove the special constraint for SW13 and SW16, keeping only the original SW potential.

**Comment by brucefan1983** [comment]
Perhaps this is not needed, because the current implementation already supports up to three atom types, although the potential file format is quite different from that of LAMMPS. I actually find our file format less redundant and easier to understand.

**Comment by AlexGabourie** [comment]
Agreed. I don't think a more general implementation is needed at this time. If there is a more compelling reason later, the general implementation can be easily created as it only requires a few lines to change how parameters are read. No extra derivations should be needed (might need to add the 'q' parameter, but that seems to be mostly 0).

**Comment by brucefan1983** [comment]
Yes, the parameters p, q, tol in the LAMMPS version have rarely been used.
