### ISSUE TITLE
Support for virials tag in extended xyz input

### ISSUE THREAD

**Issue by erhart1** [brucefan1983/GPUMD#275]
As of version 3.4 the input structures for the `nep` executable can be provided in extended xyz format, which is very useful.
In the currently supported format the virials can be provided via the `virial` tag in the second line. Unfortunately `ase` does not write the virials but the stresses.
One can of course write a custom extended xyz writer but it could be even easier to add support for the stresses as well.
The conversion is trivial as the stress tensor in the units written by `ase` only has to be multiplied by minus times the cell volume (in Å$^3$).
Hence, would it be possible to add support for parsing the stress tensor as well?
Afaict it would only require adding a block near line 198 in `main_nep/structure.cu`, no?

**Comment by brucefan1983** [comment]
Yes, it is technieqally easy to parse `stress` too. But I have one question: when both `stress` and `virial` are present, which should be used?

**Comment by erhart1** [comment]
One could check for consistency. If the two are not consistent either throw an error or use the virial data and throw a warning.

**Comment by brucefan1983** [comment]
OK, sounds a good plan. It will go to 3.5 :-)

**Comment by erhart1** [comment]
ping @elindgren
