### ISSUE TITLE
[Feature request] Please consider adding a feature of predicting tensors in GPUMD

### ISSUE THREAD

**Issue by tamaswells** [brucefan1983/GPUMD#279]
Could you consider adding a feature of predicting tensors like polarizability tensor in the next version of GPUMD? Thank you.

**Comment by brucefan1983** [comment]
Thanks for the suggestion. This is defenitely doable. Hope to get your help in the future.

**Comment by tamaswells** [comment]
That's great. It's amazing that NEP has a close precision to the AlphaML.
