### ISSUE TITLE
record one nep.txt every 1e5 generations?

### ISSUE THREAD

**Issue by brucefan1983** [brucefan1983/GPUMD#286]
Penghua has suggested to save one `nep.txt` every 1e5 generations. Then if one trains for 5e5 generations, there will be 5 candidate NEP models that can be used for comparison. These 5 models will be named as e.g., `nep100000.txt` to `nep500000.txt`.

Or we can let the user to specify the recording interval?

The main `nep.txt` will still be updated every 100 generations.

**Comment by erhart1** [comment]
I think this is a sensible feature.
I think the dump frequency should be a parameter that can be specified in the input file.
Similarly, it could be useful to add parameters for controlling the frequency for writing RMSEs etc to stdout/`loss.out`.
