### ISSUE TITLE
nvt_nhc always gives nan 

### ISSUE THREAD

**Issue by andeplane** [brucefan1983/GPUMD#3]
I'm trying to run in NVT ensemble, but it seems like nvt_nhc does not work properly. All positions and most thermo output gives nan.

I've tried different TDamp and temperatures.

**Comment by brucefan1983** [comment]
This is strange. Could you send me your inputs?

**Comment by andeplane** [comment]
Yep. You could for instance take `examples/ex1/` and change the first run ensemble to
`ensemble nvt_nhc 1 1 0.01`

If you also print positions, all of them are nan. Am I using `nvt_nhc` wrong?

**Comment by brucefan1983** [comment]
Perhaps this is caused by the too small time constant tau_T. My convention is different from LAMMPS. Here, if you set the 3rd parameters to 0.01, it means that tau_T = 0.01 * dt, where dt is the time step. This is too small. Usually, I set the 3rd parameter to 100~1000.

So the following two are "good" choice:
ensemble nvt_nhc 1 1 200  #This uses the Nose-Hoover chain method
ensemble nvt_ber 1 1 0.01 #This uses the Berendsen method

**Comment by andeplane** [comment]
Interesting, you have the factor dt whereas I expected it to be in time units. I looked for the definition in the docs, but could not find it. 

I tested with your value of 200 and it works! Maybe add a note on this in the docs :) 

Thanks for your quick responses!

**Comment by brucefan1983** [comment]
There are some descriptions on this point in the manual. You can check the middle paragraph in page 44:

The units of temperature and pressure for this keyword are K and GPa, respectively.
The temperature coupling constant in the Berendsen method can be any positive
number less than or equal to 1 and we recommend a value in the range of [0:01; 1].
A larger number results in a faster control of the temperature. The temperature
coupling constant in the Nose-Hoover chain method is in unit of the time step
and is recommended to be in the range of [100; 1000]. Here, a larger number
results in a slower control of the temperature. The pressure coupling constant in
the Berenden method should be a small positive number in the unit system adopted
by GPUMD. We recommend a value in the range of [0:01; 0:0001]. For a stiffer
material (like diamond or graphene), one should use a smaller value. In practice,
all these parameters should be determined by try and error.

**Comment by andeplane** [comment]
Ahh I see. I actually expected it to be right where the commands were listed, but that's my fault ;) Sorry about that!
