### ISSUE TITLE
Restart NEP training question 

### ISSUE THREAD

**Issue by MES-physics** [brucefan1983/GPUMD#307]
Dear GPUMD experts,
  How are the .out files written to in the case of restarting a training run to continue?
I notice that for the loss.out file, if I add another bunch of generations in order to run to completion, the loss.out file is appended as starting with generation zero again, so the relation is overlapped instead of continuous on the plot.  Since the .out files are write-once?, how is that handled for writing the final .out files?  Is there something else I need to do to them? Do I need to delete the initial .out files before restarting?
Also, is there a way to set additional generations in the nep.in file to have the plot continue?
[lossAdd50.pdf](https://github.com/brucefan1983/GPUMD/files/9990973/lossAdd50.pdf)

Thanks a lot.

**Comment by brucefan1983** [comment]
You can simply ignore the first column (number of generations) when you
plot and calculate that by yourself. E.g., if you have M rows of output
after the restarting run is finished, you can plot the x-axis as
(1:N)*100.  (Matlab syntax)

Other out files will be overwritten every 100 or 1000 generations. You
don't need to delete any for restarting.

Zheyong

MES-physics ***@***.***> 于 2022年11月11日周五 16:54写道：

**Comment by MES-physics** [comment]
Great, thanks so much!
