### ISSUE TITLE
Conserving angular momentum

### ISSUE THREAD

**Issue by erhart1** [brucefan1983/GPUMD#309]
Here is a nice illustration that the conservation of the linear momentum works very well but that it would be useful to also conserve angular momentum 😉 

<img src="https://user-images.githubusercontent.com/19806064/201516606-3d982949-356b-4a4f-a4e8-3957b2922f0e.gif" width=400>

Simulation of a benzene molecule at 500 K over 60 ps;
four different perspectives shown.

ping @brucefan1983 @elindgren

**Comment by brucefan1983** [comment]
There is a secret keyword
```
parse_correct_velocity <interval>
```
which zeros the angular momentum every `interval` steps. 
Do you want to give a try?

**Comment by erhart1** [comment]
That actually seems to have made things worse.

| No extra keyword | With extra keyword |
|--|--|
| <img src="https://user-images.githubusercontent.com/19806064/202027669-72093a0e-afc9-4d05-a840-f6b094d80ad9.gif" width=400> | <img src="https://user-images.githubusercontent.com/19806064/202028077-eb587482-e3a6-498f-9931-ae38b8ae3820.gif" width=400> |

## Input file

```
potential nep.txt 
time_step 1.0
velocity 10.0
ensemble nvt_ber 500 500 35
dump_thermo 100
dump_position 1000
correct_velocity 1
run 60000
```

**Comment by brucefan1983** [comment]
OK, perhaps the time step is too large?

For non-PBC system, angular momutum should be conserved in NVE. Have you tried NVE with an initial temperature of 1000 K (as want the target temperature to  be 500 K)?

**Comment by brucefan1983** [comment]
Any further investigation on this? If possible, could you send me the inputs (perhaps privately) for reproducing and debugging? @erhart1

**Comment by erhart1** [comment]
I analyzed this further now and the main conclusions are
* one requires a very small time step in order to get a sensible conservation of angular moment
* stochastic thermostating completely screws up the angular momentum, leading to the ever faster spinning rings shown above

So in short this is merely an integrator issue but something to be aware of if one requires momentum to be conserved.
I compiled the results and analysis in a small GL repo for future reference.
