### ISSUE TITLE
compute_rdf

### ISSUE THREAD

**Issue by brucefan1983** [brucefan1983/GPUMD#327]
It's good to have a command to compute time-averaged radial distribution funciton.

**Comment by erhart1** [comment]
You could also delegate this rather easily to external tools such as [Ovito](https://www.ovito.org/docs/) or ASE using GUI or python.
Just adding this here as a complement as there are other functionalities that are much more difficult to accomplish and could be prioritized.

**Comment by brucefan1983** [comment]
Yes, this was aksed by someone, and I record it here.
