### ISSUE TITLE
[Feature request] Translation of atoms during trajectory

### ISSUE THREAD

**Issue by chem-william** [brucefan1983/GPUMD#340]
Would it be possible to add the possibility of linear translations of atoms in the simulation box to `gpumd`?
For example, something akin to the `deform` option, but that applies to atoms in a specified group instead of the simulation box.

I'd love to try and add to it the code myself, but I'd probably need some pointers on where to start.

**Comment by brucefan1983** [comment]
If you want to do it by yourself, you can start by looking at the implementation of `deform` within this file: https://github.com/brucefan1983/GPUMD/blob/master/src/integrate/ensemble_npt_scr.cu or https://github.com/brucefan1983/GPUMD/blob/master/src/integrate/ensemble_npt_ber.cu.

Currently, `deform` is coupled to `NPT`, and I plan to deouple them in the future. 

If you want me to do this, I will need more information for you need. Do you think your need is similar to this issue: https://github.com/brucefan1983/GPUMD/issues/256

**Comment by chem-william** [comment]
Awesome! Thank you. I'll take a look and see if I can make sense of it :-)

I'm a bit unsure what is asked for in #256 so I can't say for sure whether there is an overlap.
To give a better idea of what I want to achieve, I've included a .py script that does what I want to achieve by dropping in and out of `gpumd`:
```python
import os
from ase.io import read
from ase.io import write
import numpy as np

mol = read("./starting_system.xyz")

# write the .xyz for gpumd
write("./model.xyz", mol)

# read in the atoms that has to be fixed
og_group = mol.arrays["group"]

# run one iteration of MD
os.system("gpumd")

displacement = 0.02

# displace some atoms and re-run gpumd
for i in range(800):

    # read in the new positions and set atoms to be fixed
    new_mol = read("./movie.xyz")
    new_mol.arrays["group"] = og_group

    # displace the unit cell and some of the atoms
    cell = new_mol.get_cell()
    translation = np.zeros((len(new_mol), 3))
    translation[:, 2][-144:] += displacement
    cell[2, 2] += displacement
    new_mol.set_cell(cell)
    new_mol.translate(translation)

    # write the new positions
    write("./model.xyz", new_mol, columns=["symbols", "positions", "group"])

    # re-run gpumd
    os.system("gpumd")
```

**Comment by brucefan1983** [comment]
OK, I am not very familiar with the python way of running/calling GPUMD. Do you know if you use a NEP model, you can also use LAMMPS? Here is the LAMMPS interface for NEP: https://github.com/brucefan1983/NEP_CPU

**Comment by chem-william** [comment]
Yes, I'm using a NEP model. I'll also take a look at that interface! Thanks for the suggestion

I've looked a bit at the LAMMPS keywords and I think what I want is the `fix move`.

**Comment by chem-william** [comment]
Thanks a bunch for all the help!
As I've gotten it to work with NEP-LAMMPS interface, I'll close this issue. That also means I won't look at implementing this functionality in GPUMD

**Comment by brucefan1983** [comment]
OK, I will probably enrich this kind of features in GPUMD in the future, but I have too many things to do currently, as can be seen from the full list of issues.
