### ISSUE TITLE
Script for plotting energy/forces train and testing

### ISSUE THREAD

**Issue by MES-physics** [brucefan1983/GPUMD#343]
Hi,  I saw a page where you had the scripts for plotting the NEP vs DFT data in matplotlib, available for download with a link at the bottom of the page, and now I can't find them.
Can you please point to the page?
Thanks very much.

**Comment by brucefan1983** [comment]
Do you mean the Jupyter notebook in this folder?

https://github.com/brucefan1983/GPUMD/tree/master/examples/nep_potentials/PbTe/train

**Comment by MES-physics** [comment]
No it doesn't look the same. I'm not on a jupyter .  I don't think it was on github.
It was on some other website for GPUMD/NEP?  It shows the script on an entire page, and a link at the bottom for downloading the python script.

**Comment by brucefan1983** [comment]
Then the documentation?

https://gpumd.org/tutorials/nep_tutorial.html

**Comment by MES-physics** [comment]
It must be somewhere in the docs, but it is not this page: https://gpumd.org/tutorials/nep_tutorial.html
The matplotlib script was an entire page with a download link at the bottom.

**Comment by MES-physics** [comment]
I believe the script included a calculation for RMSE.

**Comment by brucefan1983** [comment]
Perhaps the most important thing you need to read is the documentation of the output files from the `nep` executable: https://gpumd.org/nep/output_files/

Wrting codes to analyze the outputs are then straightforward.

**Comment by MES-physics** [comment]
Thanks.

**Comment by MES-physics** [comment]
OOPs!   I found the link for those who want it.
https://pynep.readthedocs.io/en/latest/auto_examples/plot_calcefs.html

It's in the pynep docs.

**Comment by brucefan1983** [comment]
Good! For Python stuff, go for pynep and calorine (https://calorine.materialsmodeling.org/).

GPUMD itself is pure CUDA style.
