### ISSUE TITLE
output NEP results to exyz files

### ISSUE THREAD

**Issue by brucefan1983** [brucefan1983/GPUMD#350]
Users like to have the data in the various `train/test_xxx.out` files to the `train_results/test_results.xyz` files.

**Comment by erhart1** [comment]
What is the specific request?
I wonder whether it is necessary to handle this inside GPUMD.
One can easily store structure specific information in the header lines of the extended xyz file, which can be parsed using, e.g., ase.

**Comment by brucefan1983** [comment]
This is the case where some users have in mind:

If there are some outliers in the parity plot, one would like to know which structures they belong to and it seems to be hard to figure out based on the current .out files, particularly for the train_xxx.out files where the order of strucctures is not the same as that in the train.xyz file if not using the fullbatch for training. 

Does it make sense to you?

**Comment by brucefan1983** [comment]
Now I agree that this feature is not needed.
