### ISSUE TITLE
A way to choose regularization parameters automatically?  

### ISSUE THREAD

**Issue by tamaswells** [brucefan1983/GPUMD#357]
I don't know the order of magnitude of RMSE before training. So I need to tune the regularization paramerters via trial-and-error  Is there a way o choose regularization parameters automatically?  Many thanks.

**Comment by shdchen** [comment]
Perhaps, the regularization parameters could be determined automatically by the RMSE (weighted sum of the energy, force, and virial RMSEs) on-the-fly. It is under testing. Thanks.

**Comment by brucefan1983** [comment]
done in #358
