### ISSUE TITLE
removing all warp-synchronous code

### ISSUE THREAD

**Issue by brucefan1983** [brucefan1983/GPUMD#36]
Warp-synchronous code is unsafe and is already incorrect for Volta (compute capability 7.0) and newer GPU architectures. So we must change this as soon as possible.

**Comment by AlexGabourie** [comment]
Do you know what the implications are for simulations run on the Volta and newer GPU architectures?

**Comment by brucefan1983** [comment]
if compiled with compute capability 7.0, all the reduction might be wrong
according to the cuda manual.

a simple fix is to compile with compute capability 6.0 ( Pascal
architecture).



AlexG <notifications@github.com> 于 2019年8月18日周日 05:35写道：

**Comment by brucefan1983** [comment]
I have done a simple test with a small code, and it turned out that the warp-synchronous version (the version that uses the warp_reduce function frequently used in GPUMD) also gives correct results when compile with -arch=sm_70 or -arch=sm_75 in a Geforce RTX 2080ti card. So perhaps our warp_reduce function still works with Volta and Turing. 

That said, I think it's better to change the code. Actually, this will simplify the code a lot. I will do it as soon as possible.

**Comment by AlexGabourie** [comment]
That's good news and thank you for checking that. I have run many simulations with CC 7.0 and 7.5. When I get a chance, I'll rerun some simulations (compiled with CC 6.0) to double check that the results are equivalent.

**Comment by brucefan1983** [comment]
Hope your results are not affected. I have removed warp_reduce completely. I also updated the examples in examples/gpumd/.

**Comment by brucefan1983** [comment]
Yes, I think Nvidia is not so crazy to make all old codes invalid so
abruptly. But is has been warned in the programming guide. So I have
changed the code. BTW, after studying CUDA programming more systematically,
I feel that there is still plenty room for speeding up the code here and
there, but this is not very urgent. I also find Unified Memory Programming
very attractive. Using this, one can use the various memories from the CPUs
and GPUs within a node as a whole. Only Pascal and Volta (also Turing) GPUs
can explore this feature efficiently, but I think Kepler will be used less
and less in the future. When Kepler disappears, we can consider  Unified
Memory Programming, which means that there are two sets of variables (one
on the GPU and one on the CPU) and explicit memory copies any more, and the
usable memory is not limited to that of a single GPU.

**Comment by brucefan1983** [comment]
This is fixed. So I close it.
