### ISSUE TITLE
Different activation functions

### ISSUE THREAD

**Issue by chem-william** [brucefan1983/GPUMD#373]
Has there been any experiments with different activation functions? I saw #129, but nothing was reported on the effect of changing the activation function.
I'm thinking in terms of performance and accuracy. For example, what if ReLU was used instead of `tanh`?

The reason is that I have some very long simulations that might benefit from even minor optimizations.

**Comment by brucefan1983** [comment]
I have tried a few, but have not found one better than `tanh`. Here the activation function has negligible effect on the computational speed: `tanh` is not more expensive than `relu` in GPU. If you want to do experiments, the function `apply_ann_one_layer` in `src/utilities/nep_utilities.cuh` is the only one you need to modify.

**Comment by chem-william** [comment]
Awesome, thank you! I'll give it a try and report what I find

**Comment by chem-william** [comment]
You were right. Doing the following in `src/utilities/nep_utilities.cuh`
```diff
- float x1 = tanh(w0_times_q - b0[n]);
- float tanh_der = 1.0f - x1 * x1;
+ float x = w0_times_q - b0[n];
+ float x1 = fmaxf(0.0f, x);
+ float relu_der = x > 0;
energy += w1[n] * x1;
for (int d = 0; d < N_des; ++d) {
- float y1 = tanh_der * w0[n * N_des + d];
+ float y1 = relu_der * w0[n * N_des + d];
energy_derivative[d] += w1[n] * y1;
}
```
and also making the following change in `https://github.com/brucefan1983/NEP_CPU/blob/main/src/nep.cpp`:
```diff
- double x1 = tanh(w0_times_q - b0[n]);
+ double x = w0_times_q - b0[n];
+ double x1 = std::max(0.0, x);
+ double relu_der = x > 0.0;
latent_space[n] = w1[n] * x1; // also try x1
energy += w1[n] * x1;
for (int d = 0; d < dim; ++d) {
- double y1 = (1.0 - x1 * x1) * w0[n * dim + d];
+ double y1 = relu_der * w0[n * dim + d];
energy_derivative[d] += w1[n] * y1;
}
```

makes no difference in the execution speed of NEP_CPU

**Comment by brucefan1983** [comment]
Thanks for the testing. One way of speeding up NEP further is to use spline for the `g_n` radial functions in the descriptor. I have some tests showing that it can speed up by 20% or more, depending on the hyperparameters, but the code is still dirty and is not ready to publish. I am also not clear how this will affect the accuracy/stability.
