### ISSUE TITLE
add velocity to NetCDF

### ISSUE THREAD

**Issue by brucefan1983** [brucefan1983/GPUMD#428]
Add an option to dump velocity to NetCDF file. @Tingliangstu

**Comment by Tingliangstu** [comment]
Will do it since NetCDF save disk space and has faster **read** speed by trajectory reader like dynasor and MDanalysis.

**Comment by brucefan1983** [comment]
@erikfransson:

 Now @Tingliangstu  will make a PR to solve this issue. I think this is also what you hoped to have!

**Comment by Tingliangstu** [comment]
Now velocities output for dump_netcdf is done.

**Comment by erikfransson** [comment]
Yes that is great, thanks!

**Comment by erikfransson** [comment]
> > Yes that is great, thanks!
> 
> @erikfransson Maybe you can test it by using dynasor. If the reader speed is faster than .exyz, that would be really helpful.

Yes we have tested  and used the previous netcdf implementation, see [here](https://dynasor.materialsmodeling.org/dev/performance.html#trajectory-reading), where we found it can be something like ~5-100x faster than reading xyz (I think the larger the system the greater the performance boost).

I have not yet tested the version with velocities, but I will try to do it next week.

Can I use it the same way as `dump_xyz`,  meaning `dump_netcdf 1000 1` (with velocities),  and  `dump_netcdf 1000 0`  (no velocities)?

**Comment by erikfransson** [comment]
@Tingliangstu  I ran a quick test and positions and velocities seems to be read correctly with netcdf trajectory format.
I tested both dynasors Trajectory-reader (uses MDAnalysis) and  ASEs netcdf reader and they gave the same positions  and velocities.

I also ran a simulation with both `dump_exyz` and `dump_netcdf` and they give the same results (xyz has a few more decimals included I think)

For consistency sake, would it make sense to rename `movie.nc` to `dump.nc`?

**Comment by erikfransson** [comment]
@Tingliangstu  I ran a quick test and positions and velocities seems to be read correctly with netcdf trajectory format.
I tested both dynasors Trajectory-reader (uses MDAnalysis) and  ASEs netcdf reader and they gave the same positions  and velocities.

I also ran a simulation with both `dump_exyz` and `dump_netcdf` and they give the same results (xyz maybe has a few more decimals included I think)

For consistency sake, would it make sense to rename `movie.nc` to `dump.nc`?

**Comment by brucefan1983** [comment]
Perhaps it is not good idea to change the filename? It is just a name. Changing it will break some user's script. movie.nc is a nice name I think.

**Comment by erikfransson** [comment]
I was thinking since `movie.xyz` is only positions but now `movie.nc` also contains velocities, meaning it is closer to `dump.xyz`.
But yes it just a filename, it doesnt matter :)

**Comment by Tingliangstu** [comment]
Yeah, it just is a name. Have you tested the read speed for NETCDF with velocities? @erikfransson

**Comment by Tingliangstu** [comment]
Well received, thanks.
