### ISSUE TITLE
Free energy calculations using thermodynamic integration

### ISSUE THREAD

**Issue by brucefan1983** [brucefan1983/GPUMD#445]
Aim to achieve it within GPUMD-v3.9.

References: 

* Tuckerman, Statistical Mechanics: Theory and Molecular Simulation (Oxford Graduate Texts)
* Christophe Chipot and Andrew Pohorille, Free Energy Calculations: Theory and Applications in Chemistry and Biology
* [Nonequilibrium free-energy calculation of solids using LAMMPS](https://doi.org/10.1016/j.commatsci.2015.10.050)
* [Automated free-energy calculation from atomistic simulations](https://doi.org/10.1103/PhysRevMaterials.5.103801)
* [Optimized Free-Energy Evaluation Using a Single Reversible-Scaling Simulation](https://doi.org/10.1103/PhysRevLett.83.3973)

**Comment by erikfransson** [comment]
@brucefan1983 Out of curiosity, what type of free energy calculations are you planning to implement? Thermodynamic integration Einstein crystal (Frenkel–Ladd path) or something beyond this?      
Another more complex but more "accurate" reference state could be a harmonic force-constant potential for which the free energy is known.

**Comment by brucefan1983** [comment]
Yes, Thermodynamic integration Einstein crystal (Frenkel–Ladd path) as in [Nonequilibrium free-energy calculation of solids using LAMMPS](https://doi.org/10.1016/j.commatsci.2015.10.050). 

I think this is a good starting point for me.

**Comment by brucefan1983** [comment]
Done in #518
