### ISSUE TITLE
EXPLORE: Make it possible to compute DOS for multiple groups .

### ISSUE THREAD

**Issue by joabro** [brucefan1983/GPUMD#47]
Background?
---------------
Currently, it is only possible to compute the DOS for the entire system or a single group. In many cases it is interesting to study the partial DOS, e.g. the contributions from all atoms of each type.

What is the current behaviour?
--------------------
The compute_dos command only accepts a single group as an optional argument.

What is the desired behaviour?
--------------------------------
It is possible to calculate the DOS for all groups of atoms defined for a specific grouping method, by providing `group group_method` as an optional argument. This means that the following command should be accepted:
```
compute_dos 8 500 55.0 group 1
```
The `dos.out` and `mvac.out` files would thus contain one column with frequencies followed by 3*N* columns with DOS and VAC data, respectively, where *N* is the number of groups in the specified grouping method.

**Comment by joabro** [comment]
cc @brucefan1983, @AlexGabourie

**Comment by brucefan1983** [comment]
This sounds a good suggestion. I think It's even a good idea to output the
per-atom vac and dos, and let the users do whatever average afterwards.

Alex, how do you think?

Zheyong

joabro <notifications@github.com> 于 2020年1月26日周日 11:47写道：

**Comment by AlexGabourie** [comment]
Certainly it is better to allow more flexibility in the output. 

@joabro If you would like to study partial DOS right now without much effort, but in an imperfect way, you can just set up multiple runs for DOS with each run focusing on a different group. This is serial and inefficient approach to the calculation, but it has been working well for me. For example, if I wanted to get the DOS for SiO2, I have one run for all atoms, another for just the Si group, and a final run for the O atom group. This allows me to get contributions from all atoms of each type.

I would have to look at the code closer, but I think that the implementation for many groups in a single DOS run will be a little more involved than my initial implementation of a single group. The single group approach easily piggybacked on the data structures already present, but the solution for many groups will need to use updated data structures. It should be very manageable though.

@brucefan1983 When you say per-atom, do you mean that we have a 1000 outputs for 1000 atoms? Or do you mean per-atom type?

**Comment by brucefan1983** [comment]
Your suggeation is very good. The time for each production run does not
need to be very long. If we use 1 ns for equilibrium, and 10 production
runs ( each with 100 ps and for a particular group), the total time is only
2 ns, which is also efficient in my opinion.

I mean per atom, not per atom type. VAC is a per atom property. But I
really think your suggestion is good and perhaps there is no need to change
the code.

Zheyong

AlexG <notifications@github.com> 于 2020年1月26日周日 20:02写道：

**Comment by joabro** [comment]
@AlexGabourie currently I am mainly interested in calculating the lattice contribution to the thermal conductivity, but I thought that it might be a good idea to take the opportunity and dump the SHC and DOS at the same time, since it might be interesting to look at these properties in order to gain further understanding, especially if the data does not agree with experiments or previous calculations. At the moment it is, hence, not essential to calculate the partial DOS.

@brucefan1983 I do not agree that the solution that @AlexGabourie proposed is efficient. This would be especially true for the systems that I am considering where there are 3 types of atoms occupying five different Wyckoff sites, e.g. Ba@2a; Ba@6d; Ga@6c; Ga@16i; Ga@24k; Ge@6c; Ge@16i and Ge@24k. If I would like to get the partial DOS for each species and site this would require 80 production runs. Also, I might be wrong but it seems a bit strange to extract the contributions to the total DOS from semi-independent runs. In the end these should sum up to the total DOS, which will only be approximately true when using this method, especially at elevated temperatures.

At least for, it would be fine if dump_dos dumped the DOS and VAC for all individual atoms, since I could then sum up the contributions to get the total as well as any partial DOS. In cases where only the total DOS is of interest, then one can simply put all the atoms in the same group (1):
```
compute_dos 8 500 55.0 group 1 1
```

In general, I think that GPUMD is doing a bit too much postprocessing since there are several cases, e.g. both the forces and the SDC, where I can only dump data for the entire system or one group of atoms even though it would  actually be preferable to get the data for all atoms in the system.

**Comment by brucefan1983** [comment]
Yes it makes sense to generalize this part. I will do it when I have time.

Zheyong

**Comment by brucefan1983** [comment]
@joabro I have just modified the code to fix this issue. It is still in an active pull request: https://github.com/brucefan1983/GPUMD/pull/65

**Comment by brucefan1983** [comment]
@joabro The feature you requested is added into the master branch and I close this issue now.
