### ISSUE TITLE
EXPLORE: Make it possible to compute SDC for multiple groups .

### ISSUE THREAD

**Issue by joabro** [brucefan1983/GPUMD#48]
Background?
---------------
Currently, it is only possible to compute the SDC for the entire system or a single group. In many cases it is interesting to study the SDC for multiple groups of atoms, for instance all of them, for the purpose of calculating, e.g. the mean-square displacements.

What is the current behaviour?
--------------------
The compute_sdc command only accepts a single group as an optional argument.

What is the desired behaviour?
--------------------------------
It is possible to calculate the SDC for all groups of atoms defined for a specific grouping method, by providing `group group_method` as an optional argument. This means that the following command should be accepted:
```
compute_sdc 8 500 group 1
```
The `dos.out` and `mvac.out` files would thus contain one column with correlation times followed by 6*N* columns with VAC and SDC data, where *N* is the number of groups in the specified grouping method.

**Comment by joabro** [comment]
cc @brucefan1983

**Comment by brucefan1983** [comment]
I am busy with finalizing my CUDA programming book. After it I will fix this issue.

**Comment by brucefan1983** [comment]
@joabro Diffusion coefficient in mixed systems is not so simple. Currently, the implementation in GPUMD only applies to the calculation of self diffusion coefficient for the whole system. I think it does not make sense to calculate the self diffusion coefficients for different groups simultaneously. If you are studying a solid, I can say for sure that the diffusion coefficient for any subsystem is zero. If your interest is in the MSD, that should be implemented separately.

**Comment by brucefan1983** [comment]
@joabro As I commented above, it is not appropriate to compute diffusion coefficients as you requested and I thus close this issue now. I may enrich the features regarding diffusion properties after I study the literature in more detail.
