### ISSUE TITLE
Add MPI support

### ISSUE THREAD

**Issue by andeplane** [brucefan1983/GPUMD#5]
For larger systems, it may be useful to run on multiple GPU's. MPI libraries can be compiled so that you can copy with memory addresses on GPU.

**Comment by brucefan1983** [comment]
Do you mean  GPUDirect? Adding MPI support would be a big change I think. I am not sure how long it will take. I don't have enough time to do it now and I also need to study the techniques first. I have no working experience with MPI. My plan was to first enrich the features of GPUMD and consider multi-GPU in the last step. After all, many of the feature of GPUMD has not been matured and there may be a lot of changes in the near future.

**Comment by andeplane** [comment]
Yep, I understand that completely :) A typical way to do it is to divide the 3 dimensional system into smaller boxes, each being owned by a process. Then some communication is required to calculate forces through the boundary between two processors, and also when atoms move from one processor to another.

I have done this before, so I might be able to help when you want to do this. I do support your plan to focus on single GPU first!

**Comment by brucefan1983** [comment]
It's very nice that you can help on this. I will come back to you when I start to do it.

**Comment by AlexGabourie** [comment]
While this feature may still be on hold for a while, I would like to put my name on the list to help when it comes time to work on it. It's a useful enhancement, definitely a bit of work, but probably a bit of fun.

**Comment by brucefan1983** [comment]
It's great you are interested in working on this issue. Do you think we should first try CUDA stream, which is able to deal with all the GPUs within a single node, or skip this and use CUDA-aware MPI directly?

**Comment by brucefan1983** [comment]
@AlexGabourie I have implemented single-node-multi-GPU version of NEP. Although there is room for improvement, I think it is what I wanted and I don't want to consider MPI any more. I like this much simpler approach, although it relies on the existence of the fast NVlink.

**Comment by AlexGabourie** [comment]
That sounds fine to me. You would know better than me, but I don't get the impression that GPUMD users would often need more GPUs than a single node can offer. If that's true, then there's not a compelling reason to pursue an MPI implementation yet.

**Comment by brucefan1983** [comment]
Yes, there are two reasons for considering multi-GPUs: 1) enabling the simulation of larger systems; 2) making one simulation faster. 

Now the single-node version can already reach a system size with 100 million atoms, and I don't think one would ever need a larger system. 

For speed, it would also be difficult to keep a decent parallel efficiency with more than 8 GPUs. 

So I believe single-node is the a sweet point and I stop here.
