### ISSUE TITLE
The input xyz.in about the FCP

### ISSUE THREAD

**Issue by ZengZezhu** [brucefan1983/GPUMD#50]
Dear Prof.Fan,

I noticed that the ex5 used the FCP from hiphive to run the gpumd, but I am confused about the input file of xyz.in: M = 1 and cutoff = 0.1.  
while for the generate_files.py, the cutoff distance is 5 angstrom. (M > 1)

Even though the cutoff parameter  is the initial cutoff distance, why we not set up a suitable value for example 5 angstrom? 

Best,

Zezhu

**Comment by brucefan1983** [comment]
Neighbor list is not used in GPUMD for the FCP potential. The neighbor list
information is hard coded into the foece constant files. You can regard the
FCP potential as a topological force field (bond, angle, dihedral...) as
those used in protein simulations.

So the parameters M and rc in xyz.in are not relevant to the simulation but
should be there. You can set rc to 5 A if you like.

Zheyong

ZengZezhu <notifications@github.com> 于 2020年2月27日周四 04:38写道：

**Comment by ZengZezhu** [comment]
Dear Prof.Fan,

Thank you for your information.I get it for this issue.

Best,
Zezhu

**Comment by brucefan1983** [comment]
You are welcome. Thanks for the question. I will close this.

Zheyong


ZengZezhu <notifications@github.com> 于 2020年2月27日周四 11:35写道：
