### ISSUE TITLE
DOC: Mention that you can read/write xyz.in files with ASE.

### ISSUE THREAD

**Issue by joabro** [brucefan1983/GPUMD#51]
Functionalities for reading and writing the GPUMD format for the structure input file, xyz.in, has recently been [introduced in ASE](https://gitlab.com/ase/ase/issues/536). This should be mentioned in the GPUMD user guide.

**Comment by joabro** [comment]
cc @brucefan1983

**Comment by brucefan1983** [comment]
Thanks! I will add this information to the manual.

Zheyong

**Comment by brucefan1983** [comment]
Do you think the following text in the manual is ok:

Recently, ASE (https://gitlab.com/ase/ase) also supported reading and
writing the xyz.in input file for GPUMD. Check the read_gpumd and
write_gpumd functions in the io module of ASE.

joabro <notifications@github.com> 于 2020年2月29日周六 12:24写道：

**Comment by joabro** [comment]
That sounds good for now. Once this functionality is included in the latest stable release one could perhaps include a link to the relevant section of the ASE user guide. I will inform you when this happens.
