### ISSUE TITLE
There are errors in the script castep2xyz.sh

### ISSUE THREAD

**Issue by woyolo990422** [brucefan1983/GPUMD#517]
There is a problem with the expression of energy and virial
After correction, as shown in the attachment
[castep2xyz-GPa.zip](https://github.com/brucefan1983/GPUMD/files/13062797/castep2xyz-GPa.zip)

**Comment by brucefan1983** [comment]
Thanks for reporting this. @Yanzhou-Wang Could you have a look?

**Comment by Yanzhou-Wang** [comment]
> There is a problem with the expression of energy and virial After correction, as shown in the attachment [castep2xyz-GPa.zip](https://github.com/brucefan1983/GPUMD/files/13062797/castep2xyz-GPa.zip)

Hi, I have carefully checked your modifed castep2xyz-GPa.sh in zipped "castep2xyz-GPa.zip" and noticed the changes at two points for expression of energy and viral. But I think original version of the script is right.

1st, energy. It is right and unnecessary to be further modified  in the line of "ener=$(grep "Final energy" $i | tail -n 1 | awk '{printf "%.6f\n", $4 - '$syst_numb_atom' * '$iso    l_ener'}')

2nd, virial, I noticed that original expression is equivalent to your modified version, Thus, it is unnecessary to make changes, either.

**Comment by brucefan1983** [comment]
As far as I understand, there is no real issue here. So I will close it.

**Comment by brucefan1983** [comment]
And thanks @Yanzhou-Wang for checking this.
