### ISSUE TITLE
CUDA Error code: 700

### ISSUE THREAD

**Issue by artempi** [brucefan1983/GPUMD#532]
I get the CUDA error when running the thermo calculation preceding the kappa calculation. This happens spontaneously, and in some cases it does and in other cases it does not terminate the run. Another observation, the code runs with Hf atoms, but crushes when Hf replaced with Zr in the .txt files. Similar error observed for SiO2 The code also runs with very small model.xyz supercell (<100 atoms ) but crushes when the cell is a little bigger (>100 atoms). Tried with different CUDA versions and compilers. Running on NVIDIA a100 GPU. Tried with 64 and 256 Gb memory so the memory does not seem to be an issue. Also tried with different versions and parameters in the nep.in file for generating the nep.txt, which did not affect the error.

CUDA Error:
    File:       ./utilities/gpu_vector.cuh
    Line:       147
    Error code: 700
    Error text: an illegal memory access was encountered

More extensive output when ran with cuda-sanitizer:

Invalid __global__ write of size 4 bytes
=========     at 0x1ed0 in find_neighbor_list_large_box(NEP3::ParaMB, int, int, int, int, int, int, Box, const int *, const int *, const int *, const double *, const double *, const double *, int *, int *, int *, int *)
=========     by thread (59,0,0) in block (9,0,0)
=========     Address 0x153d1b9c0b6c is out of bounds
=========     and is 2,541 bytes after the nearest allocation at 0x153d1b92ac00 of size 611,712 bytes
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame: [0x304e32]
=========                in /lib64/libcuda.so.1
=========     Host Frame:__cudart798 [0xea72b]
=========                in /projects/arpi3148/GPUMD/src/gpumd
=========     Host Frame:cudaLaunchKernel [0x14662b]
=========                in /projects/arpi3148/GPUMD/src/gpumd
=========     Host Frame:__device_stub__Z28find_neighbor_list_large_boxN4NEP36ParaMBEiiiiii3BoxPKiS3_S3_PKdS5_S5_PiS6_S6_S6_(NEP3::ParaMB&, int, int, int, int, int, int, Box const&, int const*, int const*, int const*, double const*, double const*, double const*, int*, int*, int*, int*) [0x67643]
=========                in /projects/arpi3148/GPUMD/src/gpumd
=========     Host Frame:NEP3::compute_large_box(Box&, GPU_Vector<int> const&, GPU_Vector<double> const&, GPU_Vector<double>&, GPU_Vector<double>&, GPU_Vector<double>&) [0x6abd5]
=========                in /projects/arpi3148/GPUMD/src/gpumd
=========     Host Frame:NEP3::compute(Box&, GPU_Vector<int> const&, GPU_Vector<double> const&, GPU_Vector<double>&, GPU_Vector<double>&, GPU_Vector<double>&) [0x6ec4f]
=========                in /projects/arpi3148/GPUMD/src/gpumd
=========     Host Frame:Force::compute(Box&, GPU_Vector<double>&, GPU_Vector<int>&, std::vector<Group, std::allocator<Group> >&, GPU_Vector<double>&, GPU_Vector<double>&, GPU_Vector<double>&, GPU_Vector<double>&, GPU_Vector<double>&) [0x63b74]
=========                in /projects/arpi3148/GPUMD/src/gpumd
=========     Host Frame:Run::perform_a_run() [0x1ae42]
=========                in /projects/arpi3148/GPUMD/src/gpumd
=========     Host Frame:Run::parse_one_keyword(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) [0x1ccde]
=========                in /projects/arpi3148/GPUMD/src/gpumd
=========     Host Frame:Run::execute_run_in() [0x1d989]
=========                in /projects/arpi3148/GPUMD/src/gpumd
=========     Host Frame:Run::Run() [0x1e0e9]
=========                in /projects/arpi3148/GPUMD/src/gpumd
=========     Host Frame:main [0xac4b]
=========                in /projects/arpi3148/GPUMD/src/gpumd
=========     Host Frame:__libc_start_main [0x23493]
=========                in /lib64/libc.so.6
=========     Host Frame:_start [0x13afe]
=========                in /projects/arpi3148/GPUMD/src/gpumd
========= Program hit cudaErrorLaunchFailure (error 719) due to "unspecified launch failure" on CUDA API call to cudaMemcpy.
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame: [0x441356]
=========                in /lib64/libcuda.so.1
=========     Host Frame:cudaMemcpy [0x1417b8]
=========                in /projects/arpi3148/GPUMD/src/gpumd
=========     Host Frame:Ensemble_NHC::integrate_nvt_nhc_2(double, double, std::vector<Group, std::allocator<Group> > const&, GPU_Vector<double> const&, GPU_Vector<double> const&, GPU_Vector<double> const&, GPU_Vector<double> const&, GPU_Vector<double>&, GPU_Vector<double>&, GPU_Vector<double>&) [0x50bf4]
=========                in /projects/arpi3148/GPUMD/src/gpumd
=========     Host Frame:Ensemble_NHC::compute2(double, std::vector<Group, std::allocator<Group> > const&, Box&, Atom&, GPU_Vector<double>&) [0x51cbe]
=========                in /projects/arpi3148/GPUMD/src/gpumd
=========     Host Frame:Run::perform_a_run() [0x1ae8f]
=========                in /projects/arpi3148/GPUMD/src/gpumd
=========     Host Frame:Run::parse_one_keyword(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) [0x1ccde]
=========                in /projects/arpi3148/GPUMD/src/gpumd
=========     Host Frame:Run::execute_run_in() [0x1d989]
=========                in /projects/arpi3148/GPUMD/src/gpumd
=========     Host Frame:Run::Run() [0x1e0e9]
=========                in /projects/arpi3148/GPUMD/src/gpumd
=========     Host Frame:main [0xac4b]
=========                in /projects/arpi3148/GPUMD/src/gpumd
=========     Host Frame:__libc_start_main [0x23493]
=========                in /lib64/libc.so.6
=========     Host Frame:_start [0x13afe]
=========                in /projects/arpi3148/GPUMD/src/gpumd

CUDA Error:
    File:       ./utilities/gpu_vector.cuh
    Line:       147
    Error code: 719
    Error text: unspecified launch failure
========= Target application returned an error
========= ERROR SUMMARY: 2 errors

**Comment by artempi** [comment]
@brucefan1983 
I have uploaded test run files.
The only difference is that the large model file is a replicated small model cell. The large one crushes while the small one runs well.

https://github.com/CUANTAM/CUDA-Error

**Comment by artempi** [comment]
@brucefan1983 Thank you for the feedback. I have uploaded test and train xyz and the loss.out into the repository. The set is made of 100 structures made from model.xyz.small with HiPhive mc-rattle (std = 0.03 and cut-off = 1.7A).

**Comment by brucefan1983** [comment]
I see. Your training data are too simple. A NEP model trained with those structures might be sufficient for calculating thermal properties basded on (static) lattice dynamics methods (such as BTE method for thermal conductivity), but cannot be expected to run stable MD simulations. To enable stable MD simulations, you need to add more training structures, particularly:
* cells with deformations (compressed, stretched structures up to, say, 5% strain; better to consider all kinds of deformations systematically). E.g., cell with both random displacements and random deformations.
* cells from realistic MD simulations in a wide range of temperatures/pressures, such as ab initio MD or MD driven by some reasonable empirical potentials (such as Tersoff if there is a good one)

Finally, you also need to do some kind of "active learning" process, but that is not mandatory.

**Comment by artempi** [comment]
@brucefan1983 That explains it. Thank you for the help!

**Comment by brucefan1983** [comment]
I close this as the issue has been understood.
