### ISSUE TITLE
AEMD

### ISSUE THREAD

**Issue by artempi** [brucefan1983/GPUMD#554]
I am looking for a way to simulate approach to equilibrium method in GPUMD. For that, initially two thermostats are introduces with different temperatures at different locations of the configuration. Later on, the thermostats are turned off and the system is let to reach state of thermal equilibrium. Is this possible to implement with the current release? I would appreciate any advice on this matter.

**Comment by brucefan1983** [comment]
Yes, it is doable with GPUMD.

* First, you define a grouping method with two groups, a group 0 and a group 1, each contianing half of the atoms in the system. 
* Then you can use the following command to create the initial temperature difference:
```
ensemble heat_nhc 300 100 80 0 1 # you can change heat_nhc to heat_bdp or heat_lan
```
This means to create a high temperature of 300+80=380 (K) for group 0 and a low tmeperature of 300-80 = 220 (K) for group 1.

* Then you can switch to nve and use the compute command to recorded the temeprature:

https://gpumd.org/gpumd/input_parameters/compute.html

**Comment by artempi** [comment]
@brucefan1983 
Thank you for a quick advice! Here is what I got:

run.in:
potential    nep.txt
ensemble heat_nhc 300 100 80 1 0
time_step    1
dump_thermo  1000
run          1000000
ensemble    nve
compute 1 100 10 temperature
run           200000

resulted in the following error:

Input Error:
    File:       measure/compute.cu
    Line:       457
    Error text: grouping method exceeds the bound.

**Comment by hailan2005** [comment]
Hi,
Please check the Error text, the grouping method error has been displayed. If you only divide into 1 grouping method, the grouping method starts from 0. So, try changing this line: "compute 0 100 10 temperature".
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Fri, Feb 2, 2024 08:23 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;Re: [brucefan1983/GPUMD] AEMD (Issue #554)

&nbsp;



 
@brucefan1983
 Thank you for a quick advice! Here is what I got:
 
run.in:
 potential    nep.txt
 ensemble heat_nhc 300 100 80 1 0
 time_step    1
 dump_thermo  1000
 run          1000000
 ensemble    nve
 compute 1 100 10 temperature
 run           200000
 
resulted in the following error:
 
Input Error:
 File:       measure/compute.cu
 Line:       457
 Error text: grouping method exceeds the bound.

**Comment by artempi** [comment]
Thank you for suggestion. In my case there are two groups: 0,1. The code runs well until the line 
compute 1 100 10 temperature
which results in error. 
Ideally I would want to do both 
compute 0 100 10 temperature
compute 1 100 10 temperature
if that's also an option.

**Comment by artempi** [comment]
Update: 
It works for 
compute 0 100 10 temperature
but not for 
compute 1 100 10 temperature
even though there are two groups, 0 and 1.

**Comment by hailan2005** [comment]
Look at the online manual in detail and don't confuse the number of groups and the grouping methods



&nbsp;&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Fri, Feb 2, 2024 10:47 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [brucefan1983/GPUMD] AEMD (Issue #554)

&nbsp;



 
Update:
 It works for
 compute 0 100 10 temperature
 but not for
 compute 1 100 10 temperature
 even though there are two groups, 0 and 1.

**Comment by artempi** [comment]
Thank you for help! I just realized that.

**Comment by brucefan1983** [comment]
The velocity keyword is missing in the beginning.

**Comment by brucefan1983** [comment]
I suggest you read through this page to fully understand "a grouping method" and "groups in a grouping method": https://gpumd.org/gpumd/input_files/model_xyz.html

**Comment by brucefan1983** [comment]
Has your problem solved? @artempi 
Do you have more questions regarding AEMD?
