### ISSUE TITLE
Header needs update in the dipole moment example file

### ISSUE THREAD

**Issue by naik-aakash** [brucefan1983/GPUMD#558]
# Summary
Currently,  the example file for the trained dipole moment model is not up to date to match recent changes in nep.

The header in the \`nep.txt\` file should be rewritten as `nep4 6 H C N O S Cl -> nep4_dipole 6 H C N O S Cl`.

This leads to errors when using nep model in ASE  as calculator. Specifically `PropertyNotImplementedError: dipole property not implemented`

# Steps to reproduce the error

Follow the tutorial [here](https://calorine.materialsmodeling.org/tutorials/calculators.html) for calculating the dipole moments using example model [files](https://github.com/brucefan1983/GPUMD/tree/master/examples/12_NEP_dipole_QM7B) from this repository.

**Comment by erhart1** [comment]
@naik-aakash this appears to be an issue in the `calorine` rather than `gpumd`. Can you post the issue [there](https://gitlab.com/materials-modeling/calorine)?

**Comment by naik-aakash** [comment]
Hi @erhart1, I did report it first there, but as per one of the developer, its due to headers in nep.txt being not up to date in the example file here.

**Comment by erhart1** [comment]
My bad. You are correct

**Comment by brucefan1983** [comment]
Yes, will update those files.

**Comment by brucefan1983** [comment]
I have done it in this PR: https://github.com/brucefan1983/GPUMD/pull/559

**Comment by naik-aakash** [comment]
Thanks @brucefan1983 ! Will close this issue then :smiley:
