### ISSUE TITLE
cutoff distance in NEP.txt files

### ISSUE THREAD

**Issue by jschindler89** [brucefan1983/GPUMD#570]
Hi,

I notice that the output files for NEP3 have 4 cutoff numbers vs 2 in NEP2 files. 

May I ask you what the additional two numbers are in NEP3?

Thanks,

Jack

**Comment by brucefan1983** [comment]
The additional two numbers are the maximum numbers of neighbors within the radial and angular cutoff radii, respectively, as determined by the training dataset. You can check that they are consistent with screen output during the training. They are used to estimate the memory to be allocated for some arrays in the code such that there will be no risk of exceeding the array size during normal MD and also no waste of memory. 

The two extra numbers in **nep.txt** are actually applicable to any versions of NEP (NEP2, NEP3, and NEP4) now. If you have one **nep.txt** file without such extra numbers, it means that it was obtained by using a very old version of GPUMD (perhaps before version 3.4). To make them consistent with the newer GPUMD versions, you can try to add those extra numbers by yourself, referring the screen output I mentioned, or just based on your estimation for the systems.

**Comment by jschindler89** [comment]
Thank you so much for your quick reply. 

I tried to run some simulations but I get the following error below. Would you happen to have any suggestions? My simulation cell size is ~ 80 Angstroms made of 40,000 atoms or so. I am trying to use 4 GPUs. 

Jack

"The longest direction has less than 5 times of the NEP cutoff per GPU.
Please reduce the number of GPUs or increase the simulation cell size."

**Comment by brucefan1983** [comment]
With 4 GPUs, the code will first try to divide the system into 4 pieces along one direction, each being about 20 Angstrom for your system. This might be only 3*radial_cutoff for a typical NEP model, hence the error message you saw. GPUMD requires larger size for each piece to work. So for your system size, you may only be able to use 2 or 3 GPUs (you can try). 

The choice made by GPUMD is very reasonable. Using 4 GPUs for your (relatively small) system will not result in a significant speedup (might well be a slowdown if it were allowed to run with 4 GPUs) compared to using 2 or 3 GPUs, and GPUMD thus refuses to continue with it.

**Comment by jschindler89** [comment]
Ah I understand. Thank you for the clarifications!!
