### ISSUE TITLE
ensemble npt and F_e

### ISSUE THREAD

**Issue by jschindler89** [brucefan1983/GPUMD#572]
Hi,

I have some questions on ensemble npt_scr. I think the first three numbers are T1, T2, and T_coup. Can I ask you what the next three numbers are? I think the last one is p_coup but not sure what the other ones are.

One additional question is how do I know whether or not F_e (perturbation with Angstrom^-1) is good enough? It appears that sometimes too small F_e may not be good but I guess there is also an upper limit to F_e. 

Thanks,

Jack

**Comment by brucefan1983** [comment]
* The `ensemble npt_scr` keyword is documented here: 

https://gpumd.org/gpumd/input_parameters/ensemble_standard.html

* The choice of Fe has been discussed in the original article: 

   https://doi.org/10.1103/PhysRevB.99.064308

  See Fig. 3a and related discussion.  You can also check the supplementary of this article:

  https://doi.org/10.1103/PhysRevB.107.054303

So if you run sufficiently long HNEMD simulations, you can easily find a "good" parameter that does not lead to "divergence" (which usually means non-lineaer response) while also gives sufficient signal.

That said, sufficiently stretched 2D materials are special, for which $\kappa$ **might** not converge at all, no matter how small Fe is.

**Comment by jschindler89** [comment]
Thank you very much. 

I did look at the keyword documentations but I wasn't sure what C_hydro represents. Would you please elaborate on C_hydro? Is 10 to 50 for this value adequate?

Thank you for your comments on the convergence.

Regards,

Jack

**Comment by brucefan1983** [comment]
C_hydro is used when you want to treat the system as isotropic and it represents an estimation of the modulus scaler, which is inverse of the compressibility. It does not need to be exact; a rough estimate is ok. For example, one can use 1000 GPa for graphene, 100 GPa for many solids, 10 GPa  for softer systems. In the code, it is the product of the modulus and p_coup that controls the NPT algorithm. So choosing a too small value for the modulus might cause violent box re-scaling, and in choosing a too large value for moculus is equivalent to increasing p_coup, which usually does not lead to too bad outcomes. 

You can try and observe the data in thermo.out. This is the fastest way to gain experiences.

**Comment by jschindler89** [comment]
Thank you very much. I will play around the values and study.

Jack
