### ISSUE TITLE
units of input stress in trian.xyz/test.xyz

### ISSUE THREAD

**Issue by brucefan1983** [brucefan1983/GPUMD#580]
It seems the input stress in `train.xyz/test.xyz` should be eV/Angstrom^3, not GPa as currently mentioned in the manual. Could you confirm it? @elindgren

**Comment by elindgren** [comment]
@brucefan1983 Yes I think you are correct. Looking at the code we directly convert the stress to per-atom virials by dividing with the volume (in Å^3) and number of atoms. If the stress was in GPa there should additionally be a conversion factor. 

https://github.com/brucefan1983/GPUMD/blob/8cdb6a4fc5bf05ffb3ea32f3435ec1bac7508efb/src/main_nep/structure.cu#L228-L235
