### ISSUE TITLE
cudaErrorIllegalAddress: an illegal memory access was encountered

### ISSUE THREAD

**Issue by xinyu1905** [brucefan1983/GPUMD#583]
I encountered the following error while computing the thermal conductivity of PbTe using gpumd. Could you please advise on the cause?
……
Initialized velocities with T = 300 K.
Use NVE ensemble for this run.
Time step for this run is 1 fs.
Dump thermo every 10 steps.
Run 10000 steps.
    1000 steps completed.
    2000 steps completed.
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  exclusive_scan failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
已放弃 (核心已转储)
[PbTe_input.zip](https://github.com/brucefan1983/GPUMD/files/14811962/PbTe_input.zip)

**Comment by brucefan1983** [comment]
This usually means the simulation is not stable. There are two probable reasons for this:
* The potential (if it is an NEP model) is not very stalble for the purpose.
* The initial structure is not very good.

**Comment by xinyu1905** [comment]
i performed thermal conductivity calculations by expanding the  supercell on the structures used to train the NEP potential, but meet the error above. if i use the structure in the GPUMD package, the error disappeared

**Comment by brucefan1983** [comment]
So you used the NEP model in the example? This one: https://github.com/brucefan1983/GPUMD/tree/master/examples/11_NEP_potential_PbTe

**Comment by xinyu1905** [comment]
no, the NEP model was trained using AIMD data that I ran myself, with training parameters based on examples from GPUMD. The relevant files are provided in my question. when I expand the cell using my POSCAR file and run thermal conductivity calculations, i encounter errors. however, using the model.xyz file provided in the GPUMD examples does not result in any errors.

**Comment by brucefan1983** [comment]
OK, I have tested with your provided NEP model and inputs. I think it is becasue your training data are too simple. You might have only a short AIMD trajectory sampled at 300 K. 

Chaning to use the NEP model in the PbTe example, I can achieve stable MD running with your model.xyz.

**Comment by brucefan1983** [comment]
Even the training data in the PbTe example is very simple. It just contains some fixed-cell structures from a AIMD runs up to 900 K.

Training data are very important. A "good" training data set should consists of structures produced under various conditions.

**Comment by xinyu1905** [comment]
very thanks to your response， I will test it following your suggestions

**Comment by brucefan1983** [comment]
OK, I iwll close this issue. You can reopen it or create another one if you have more questions.
