### ISSUE TITLE
Error when compiling GPUMD with netCDF

### ISSUE THREAD

**Issue by joabro** [brucefan1983/GPUMD#59]
When trying to compile GPUMD with netCDF support one gets the following error message:
```
measure/dump_netcdf.cuh(71): error: identifier "Atom" is undefined

1 error detected in the compilation of "/scratch/tmpxft_000b7c80_00000000-6_measure.cpp1.ii".
makefile:100: recipe for target 'measure/measure.o' failed
make: *** [measure/measure.o] Error 1
```

**Comment by joabro** [comment]
cc @AlexGabourie, @brucefan1983

**Comment by brucefan1983** [comment]
@joabro 
I have just tried to fix this error, but I did without testing, because I have not installed netCDF. You could try again, and Alex is also planning to test this soon.

**Comment by joabro** [comment]
Though the first error disappears I now receive this error instead:
```
measure/dump_netcdf.cu(259): error: a value of type "const double *" cannot be used to initialize an entity of
 type "double *"

1 error detected in the compilation of "/scratch/tmpxft_000c195e_00000000-6_dump_netcdf.cpp1.ii".
makefile:100: recipe for target 'measure/dump_netcdf.o' failed
make: *** [measure/dump_netcdf.o] Error 1
```

**Comment by brucefan1983** [comment]
Thanks for pointing the problem. I have just fixed it (again, without compiling the code). I am sorry for these inconveniences for you. I have recently refactored the whole code a lot, without installing netCDF and testing this part.

**Comment by joabro** [comment]
In can now compile GPUMD without receiving any errors. Thank you for taking care of this so quickly. You can close this issue.

**Comment by brucefan1983** [comment]
Thanks. I will close it.
