### ISSUE TITLE
The keyword "velocity" in "run.in" to initialize the velocities of the system atoms might be given a reference value  by default.

### ISSUE THREAD

**Issue by Yanzhou-Wang** [brucefan1983/GPUMD#607]
It is possibly forgotten to set a  initial "velocity" (temperature) in file "run.in" by users. It might be more friendly to users who forget accidentally or omit the keyword on purpose if a smart reference value can be given as a default in GPUMD.

**Comment by brucefan1983** [comment]
fixed in #653
