### ISSUE TITLE
Questions about NEP descriptors，Why is there an extra factor（2） in the derivation?

### ISSUE THREAD

**Issue by gengxingze** [brucefan1983/GPUMD#623]
For two-body descriptors

$G_r = \sum_{j} e^{-\eta(R_{ij} - R_s)^2 \cdot f_c(R_{ij})}$

Using the following two operations is equivalent
1.
```
            grad_desc[page + numnei * DIM + dim] -= pair;
            grad_desc[page + jj * DIM + dim] += pair;
```
2.
```
atom.fx[n1] += f12[0];
atom.fy[n1] += f12[1];
atom.fz[n1] += f12[2];
atom.fx[n2] -= f12[0];
atom.fy[n2] -= f12[1];
atom.fz[n2] -= f12[3];

```

 For multi-body BP descriptors

$G_a = 2^{1-\xi} \sum_{j } \sum_{k } (1 + \lambda \cos \theta_{ijk})^{\xi} \times e^{-\eta(R_{ij}^2 + R_{ik}^2 )} \times f_c(R_{ij}) \cdot f_c(R_{ik})$

The derivation process generally requires the derivation of rij, rik, and rjk, and then assigning the values with a code similar to the following, with ‘pair’ denoting the derivation
```
              grad_desc[page + numnei * DIM + dim] += -pair_ij - pair_ik;
              grad_desc[page + jj * DIM + dim] += pair_ij - pair_jk;
              grad_desc[page + kk * DIM + dim] += pair_ik + pair_jk;
```
But in the NEP multibody descriptor, as follows, the same three indicators i,j,k appear but are derived only for rij

$q_i^{nl} = \sum_{j \neq i} \sum_{k \neq i} g_n(r_{ij}) \cdot g_n(r_{ik}) \cdot P_l(\cos \theta_{ijk}) $

The derivation in the GPUMD paper is as follows：

$\frac{\partial q_i^{nl}}{\partial r_{ij}} = 2 \sum_{k \neq i} \frac{\partial g_n(r_{ij})}{\partial r_{ij}} g_n(r_{ik}) \frac{r_{ij}}{r_{ik}} P_l(\cos \theta_{ijk}) + 2 \sum_{k \neq i} g_n(r_{ij}) g_n(r_{ik}) \frac{\partial P_l(\cos \theta_{ijk})}{\partial \cos \theta_{ijk}} \times \frac{1}{r_{ij}} \left( \frac{r_{ik}}{r_{ik}} - \frac{r_{ij}}{r_{ij}} \cos \theta_{ijk} \right) $

Why is there an extra factor of 2 here and no need to derive it for the ik and jk indicators?

**Comment by brucefan1983** [comment]
Moreover, the expression for $\partial q _i / \partial \mathbf{r} _{ij}$ in my 2021 PRB paper for NEP is not the exact one used for programming. It involves double summations over neighbors, which is quite expensive for large cutoff radius. The actually implementation used spherical harmonics instead of Legendre polynomials (I have used Legendre polynomials in the early prototyping process and they gave equivalent results).

**Comment by gengxingze** [comment]
So for a BP descriptor such as :

$G_i=2^{1-ζ} ∑_{(j,k≠i)} (1+λcosθ_{ijk})^{ζ}e^{-η(R_{ij}^2+R_{ik}^2 ) }*f_c (R_{ij} ) f_c (R_{ik})$
如果令

$P(\cos\theta_{ijk}) = 2^{1-\xi} (1+\lambda \cos\theta_{ijk})$

$g_n(r_{ij})=e^{-ηR_{ij}^2}f_c (R_{ij})$

then

$G=∑_{(j,k≠i)}P(\cos\theta_{ijk})g_n(r_{ij})g_n(r_{ik})$

Similar to NEP, only ij is derived:

$\frac{\partial G}{\partial r_{ij}} =  \sum_{k\neq i} \frac{\partial g_n(r_{ij})}{\partial r_{ij}} g_n(r_{ik}) \frac{r_{ij}}{r_{ij}} P_l(\cos\theta_{ijk}) + \sum_{k\neq i} g_n(r_{ij}) g_n(r_{ik}) \frac{\partial P_l(\cos\theta_{ijk})}{\partial \cos\theta_{ijk}} \times \frac{1}{r_{ij}} \left( \frac{r_{ik}}{r_{ik}} - \frac{r_{ij}}{r_{ij}} \cos\theta_{ijk} \right)$

Then carefully multiplying by the factor 2, the final force can be written as

$F_{ij}  = \frac{\partial U_i}{\partial r_{ij}} - \frac{\partial U_j}{\partial r_{ji}}$

At this point we then do not need to derive the ik and jk indicators?

**Comment by brucefan1983** [comment]
> by the factor 2, the final force

Yes. Note that you need to first compute all the $\lbrace \partial U _i / \partial \mathbf{r} _{ij} \rbrace$, store them in memory and get $\partial U _j / \partial \mathbf{r} _{ji}$ when you need them.
