### ISSUE TITLE
A BUG of compute_rdf

### ISSUE THREAD

**Issue by zhyan0603** [brucefan1983/GPUMD#645]
There might be a bug in the RDF calculation for the small cell. I found differences in the radial distribution function (RDF) calculations performed by GPUMD's `compute_rdf` command for different supercells (111, 222, and 333). 

<img width="424" alt="37aec0c1d0432d48aa6a87f0ef18bcb" src="https://github.com/brucefan1983/GPUMD/assets/119929382/9d916f45-80ff-4e36-85fe-a8f418e41a8c">

**Comment by brucefan1983** [comment]
fixed in #649
