### ISSUE TITLE
Adding reminder to check the input xyz file.

### ISSUE THREAD

**Issue by yyxwjq** [brucefan1983/GPUMD#682]
When using NEP to train the MLP, there is some information missing in the input xyz file, causing the RMSE in the loss.out file to be nan. Maybe it's useful to check whether the input files missing some of the information firstly, and when this is encountered to just abort the program and report the error?
![{3880A854-FFD3-40a4-AAB8-F1D941F129E0}](https://github.com/user-attachments/assets/4ea3c88b-e7ea-4ad9-a701-6f79ea8a2cd0)
![{F8D3B098-E528-4521-B282-65BFA2018A22}](https://github.com/user-attachments/assets/73f8e0c8-3d4e-427f-98d6-0b00bdaf527a)

**Comment by brucefan1983** [comment]
Thanks for the suggestion!

**Comment by brucefan1983** [comment]
Now the code can detect `nan` and `inf`, see #697

**Comment by brucefan1983** [comment]
@yyxwjq
