### ISSUE TITLE
Suggestion: Allow compression of netCDF (movie.nc) files.

### ISSUE THREAD

**Issue by joabro** [brucefan1983/GPUMD#69]
Currently, the netCDF files created when supplying the keyword dump_netcdf are not compressed, even though this is supported in the recommended version (4.6.3). Since it is more convenient to perform the compression when creating the files instead of leaving it in the hands of the user, as a post-process step, I would suggest that a "compress" option is introduced, which might include additional parameters such as compression (deflate) level and chunk size. Additional information can be found [here](http://climate-cms.wikis.unsw.edu.au/NetCDF_Compression_Tools)

**Comment by brucefan1983** [comment]
I think netCDF will not be maintained in the future. At least I am not able to do anything about it. Externel dependence is very hard to maintain and this is why I tried my best to keep GPUMD a stand-alone code.
