### ISSUE TITLE
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:

### ISSUE THREAD

**Issue by flatimewt** [brucefan1983/GPUMD#738]
How to fix the compile error?

**Comment by brucefan1983** [comment]
This is probably a problem of the mismatch between CUDA and GCC. You can try to use other combinations as you have. Here is a relevant link:

https://stackoverflow.com/questions/74350584/nvcc-compilation-error-using-thrust-in-cuda-11-5

**Comment by brucefan1983** [comment]
As far as I understand, this is not a GPUMD problem, but a CUDA toolkit problem. So I close it.
