### ISSUE TITLE
Neighbor number is larger than 1024

### ISSUE THREAD

**Issue by mushroomfire** [brucefan1983/GPUMD#739]
When the NEP model exceeds the maximum neighbor number of 1024 (due to CUDA kernel thread limitations), the code throws the following error:
"Invalid configuration argument."

- Solution:
Reduce the neighbor number in the NEP model to below 1024.

- Expected behavior:
Provide a clearer error message, such as:
"The neighbor number exceeds the maximum limit of 1024. Please reduce it."

**Comment by brucefan1983** [comment]
Thanks. This is a good suggestion.
