### ISSUE TITLE
Example 12 and Example 13 Throw nan in Total-Loss Column

### ISSUE THREAD

**Issue by BBBuZHIDAO** [brucefan1983/GPUMD#763]
Hello, I pulled the lasted code and tested the example 12 and 13 in `example` directory. The total loss column always showed `nan`. I just modified the compiling `CUDA_ARCH` to `sm_89` and used less generation to test. Are there any other steps I missed? (or maybe the examples need to update)

Output files:
[gpumd.out.example_12.txt](https://github.com/user-attachments/files/17472131/gpumd.out.example_12.txt)
[gpumd.out.example_13.txt](https://github.com/user-attachments/files/17472135/gpumd.out.example_13.txt)
![image](https://github.com/user-attachments/assets/ba60ca97-4f73-4415-9fd0-addb94c24016)

Thank you all!

**Comment by brucefan1983** [comment]
Yes, this is a harmless but elusive bug that I have no idea what's going on. I have never reproduced it.
