### ISSUE TITLE
Update documentation of compute.out file

### ISSUE THREAD

**Issue by EsmeeBerger** [brucefan1983/GPUMD#782]
In relation to the update of the compute command documentation to include the momentum (#764), could you please also update the documentation of the compute.out file accordingly? In particular, I'm wondering if the order is the same as the other quantities (p_x1 ... p_xM p_y1 ... p_yM p_z1 ... pzM) and what the unit of the computed momentum is?

**Comment by brucefan1983** [comment]
Thanks for the question. The data are stored in the order you presented. The units for moemtum are Dalton^(1/2) eV^(1/2).

If you like I encourage you to create a pull request to update the document (after you confirmed the above statements). Then you become a developer :-)
