### ISSUE TITLE
pair_wise_cutoff and illegal memory access during nep training

### ISSUE THREAD

**Issue by rebeltroopers** [brucefan1983/GPUMD#788]
Hello,

I am doing some items with the pair_wise_cutoff of gpumd v 3.9.5. My training of nep training is only around 2G of memory usage, computer has 16Gb. It is small and contains around 3000 frames. I set an nep.in with cutoff of 3.8 3.8 and pair_wise_cutoff of 2.2 2.2. This will lead to illegal memory access and crash. However if I do the same with cutoff = 3.8 3.8 and pair_wise_cutoff of 2.3 2.0 it works. The issue seems to be in radial term of the pair_wise_cutoff as it must be decently lower radial term. From the documentation it did not seem to be directly stating that this is a requirement. Not sure if this is a bug or an undocumented feature or an error on my part.

Specific error
```UDA Error:
    File:       main_nep/nep3.cu
    Line:       1013
    Error code: 700
    Error text: an illegal memory access was encountered```

**Comment by brucefan1983** [comment]
Yes, there was a bug for this feature which has been fixed some time ago in the master version. https://github.com/brucefan1983/GPUMD/pull/736

Could you try the current master version?
